# 项目名称
project_name: xxx项目名称

env: 测试环境
# 测试人员名称，作用于自动生成代码的作者，以及发送企业微信、钉钉通知的测试负责人
tester_name: fay

# 域名1
host: http://hn216.api.yesapi.cn/api/App/User
# 域名2，支持多个域名配置
app_host:

# 开发者应用的app_key,固定不变
appkey: 0DF5B8C9BE5133A6C86CC4A024D03A98


